channels:
- pytorch
- defaults
- conda-forge
dependencies:
- python=3.10.6
- pip=22.3.1
- pytorch
- torchvision
- numpy
- Pillow
- matplotlib
- torchtext
- pycocotools
- pip:
    - visual-genome
    - opencv-python